name: ✨ Feature Request
description: Suggest an enhancement to the build system or infrastructure
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please note: This template is for **build system and infrastructure** features.

        For **academic content** (paper corrections, new arguments, etc.), please see our [Contributing Guide](https://github.com/realnedsanders/Coordination-Trilemma/blob/main/CONTRIBUTING.md).

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have searched [existing issues](https://github.com/realnedsanders/Coordination-Trilemma/issues) to ensure this hasn't been requested
          required: true
        - label: I have read the [documentation](https://github.com/realnedsanders/Coordination-Trilemma/tree/main/docs)
          required: true
        - label: This is a build/infrastructure feature (not paper content)
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Build system improvement
        - CI/CD workflow enhancement
        - Docker image optimization
        - Documentation improvement
        - Security enhancement
        - Developer experience
        - Performance optimization
        - Testing infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I think we should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - New users would benefit by...
        - Maintainers would save time by...
        - Build times would improve by...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could be implemented by:
        1. ...
        2. ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking my work
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: |
        - Similar projects do this by...
        - This would help with...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this?
      options:
        - label: I'm willing to submit a PR to implement this feature
