name: 📄 Paper Content Issue
description: Report errors, suggest improvements, or discuss the academic paper content
title: "[Paper]: "
labels: ["paper-content", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for engaging with the academic content! This template is for issues related to the **paper's arguments, proofs, and academic content**.

        For build/infrastructure issues, please use the Bug Report or Feature Request templates.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have read the [latest published PDF](https://enlightenment.dev/main.pdf)
          required: true
        - label: I have searched [existing issues](https://github.com/realnedsanders/Coordination-Trilemma/issues) for similar content discussions
          required: true
        - label: I have read the [Contributing Guide](https://github.com/realnedsanders/Coordination-Trilemma/blob/main/CONTRIBUTING.md)
          required: false

  - type: dropdown
    id: content-type
    attributes:
      label: Issue Type
      description: What kind of content issue is this?
      options:
        - Mathematical error or incorrect proof
        - Logical inconsistency
        - Missing citation or reference
        - Historical inaccuracy
        - Unclear argument or explanation
        - Suggestion for additional content
        - Counterexample or alternative view
        - Terminology or definition issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: Affected Section
      description: Which part of the paper is this about?
      options:
        - Abstract
        - Introduction / Overview
        - Section 1-3 (Trilemma definition)
        - Section 4-6 (Corruption-Control Cycle)
        - Section 7-9 (Voluntary Coordination)
        - Appendix A (Why No Alternative)
        - Appendix B (Mathematical Foundations)
        - Appendix C (Defense Mechanisms)
        - Appendix D (Closing Window)
        - Bibliography
        - Multiple sections
        - Entire paper
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Clearly describe the problem or suggestion
      placeholder: |
        In Section 3, the proof assumes X, but this doesn't account for Y...
        OR
        The paper doesn't address the case where...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence or Reasoning
      description: Provide evidence, citations, or detailed reasoning
      placeholder: |
        - Research by [Author et al., Year] shows that...
        - Historically, [example] demonstrates...
        - The mathematical proof fails when...
      render: markdown

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: If applicable, what change would address this issue?
      placeholder: |
        The paper should:
        - Clarify that...
        - Add a caveat about...
        - Include evidence from...
        - Revise the proof to...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How significant is this issue?
      options:
        - Critical - Undermines main argument
        - Major - Significant flaw or gap
        - Moderate - Important clarification needed
        - Minor - Small error or improvement
        - Trivial - Typo or formatting
    validations:
      required: true

  - type: textarea
    id: related-work
    attributes:
      label: Related Literature
      description: Are there relevant academic sources?
      placeholder: |
        Relevant papers:
        - Author, A. (Year). "Title." Journal. DOI/URL
        - Author, B. (Year). "Title." Journal. DOI/URL
      render: markdown

  - type: checkboxes
    id: core-argument
    attributes:
      label: Core Argument
      description: Does this affect the paper's main claims?
      options:
        - label: This affects the core trilemma argument
        - label: This affects the voluntary coordination proposal
        - label: This affects the metaphysical conclusions
        - label: This is about supporting evidence or examples
        - label: This is about presentation/clarity only

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - This is particularly important because...
        - This relates to recent developments in...
        - My background in this area is...

  - type: markdown
    attributes:
      value: |
        ---
        **Note:** Significant changes to the main argument require substantial justification. Please be as detailed and specific as possible.
