#!/bin/sh
# Generate build information for LaTeX document
# This script creates build-info.tex with git and build metadata

OUTPUT_FILE="build-info.tex"

# Get git information
# Check if we're in a git repository first
if git rev-parse --git-dir >/dev/null 2>&1; then
    GIT_COMMIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
    GIT_COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")

    # Check if working tree is dirty (has uncommitted changes)
    if git diff --quiet 2>/dev/null && git diff --cached --quiet 2>/dev/null; then
        GIT_DIRTY=""
    else
        GIT_DIRTY="-dirty"
    fi
else
    # Not a git repository
    GIT_COMMIT_HASH="unknown"
    GIT_COMMIT_SHORT="unknown"
    GIT_BRANCH="unknown"
    GIT_TAG=""
    GIT_DIRTY=""
fi

# Get build information
BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
BUILD_TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
BUILD_USER=${BUILD_USER:-$(whoami 2>/dev/null || echo "unknown")}
BUILD_HOST=${BUILD_HOST:-$(hostname 2>/dev/null || echo "unknown")}

# CI-specific information
if [ -n "$GITHUB_ACTIONS" ]; then
    BUILD_PLATFORM="GitHub Actions"
    BUILD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
    BUILD_ID="${GITHUB_RUN_NUMBER}"
else
    BUILD_PLATFORM="local"
    BUILD_URL=""
    BUILD_ID="local"
fi

# Create LaTeX file with build information
cat > "$OUTPUT_FILE" << EOF
% Auto-generated build information
% DO NOT EDIT - This file is generated by generate-build-info.sh

% Build metadata commands
\newcommand{\BuildCommitHash}{$GIT_COMMIT_HASH}
\newcommand{\BuildCommitShort}{$GIT_COMMIT_SHORT}
\newcommand{\BuildBranch}{$GIT_BRANCH}
\newcommand{\BuildTag}{$GIT_TAG}
\newcommand{\BuildDate}{$BUILD_DATE}
\newcommand{\BuildTimestamp}{$BUILD_TIMESTAMP}
\newcommand{\BuildUser}{$BUILD_USER}
\newcommand{\BuildHost}{$BUILD_HOST}
\newcommand{\BuildPlatform}{$BUILD_PLATFORM}
\newcommand{\BuildURL}{$BUILD_URL}
\newcommand{\BuildID}{$BUILD_ID}
\newcommand{\BuildDirty}{$GIT_DIRTY}

% Formatted build info for footer
\newcommand{\BuildInfo}{%
    \texttt{\BuildCommitShort\BuildDirty} built on \BuildDate%
    \ifx\BuildURL\empty\else\ (\href{\BuildURL}{CI \#\BuildID})\fi%
}

% SLSA-style provenance for PDF metadata
\hypersetup{
    pdfproducer={pdfLaTeX via \BuildPlatform},
    pdfcreator={Coordination Trilemma Build System},
    pdfsubject={Built from commit \BuildCommitHash},
    pdfkeywords={git-commit:\BuildCommitHash, git-branch:\BuildBranch, build-date:\BuildTimestamp, builder:\BuildPlatform}
}
EOF

echo "Generated $OUTPUT_FILE with build metadata"
